import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hana
 */
public class FrameMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrameMenu
     */
    public FrameMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        strpin = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setText("PILIH MENU");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Masukkan angka menu");

        jLabel1.setText("[1] INFORMASI SALDO");

        jLabel2.setText("[2] PENYETORAN");

        jLabel3.setText("[3] PENARIKAN");

        jLabel4.setText("[4] PETUNJUK");

        jLabel5.setText("[5] KELUAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(strpin, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(strpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String str, setor;
        int str1, tab=50000, setor1, tab1 ;
        str = strpin.getText();
        str1 = Integer.parseInt(str);

        switch(str1)
        {
            //kode pengecekan saldo
            case 1:
            if(strpin.getText().equals(""))
            {JOptionPane.showMessageDialog(null,"Silakan isi PIN anda","ERROR",1);}
            JOptionPane.showMessageDialog(null,"Saldo Anda saat ini sebesar : " + tab);
            strpin.setText("");
            break;

            //kode penyetoran
            case 2:
            //dialog input
            if(strpin.getText().equals(""))
            {JOptionPane.showMessageDialog(null,"Silakan isi PIN anda","ERROR",1);}
            setor = JOptionPane.showInputDialog(null,"Masukkan jumlah penyetoran: " );
            setor1 = Integer.parseInt(setor);
            //jika kosong
            if(setor1<50000){
                JOptionPane.showMessageDialog(null,"Minimal penyetoran adalah Rp50.000");
                strpin.setText("");
            }
            //jika berhasil
            else{tab1 = tab+setor1;
                JOptionPane.showMessageDialog(null,"Penyetoran berhasil. \n Saldo anda adalah Rp."+tab1 );
                strpin.setText("");}
            break;

            //kode penarikan
            case 3:
            setor = JOptionPane.showInputDialog(null,"Masukkan jumlah penarikan: " );
            setor1 = Integer.parseInt(setor);
            //jika kosong
            if(setor==""){
                JOptionPane.showMessageDialog(null,"Penarikan Gagal. \n Isi jumlah penarikan anda" );
                strpin.setText("");
            }
            //jika kurang dari 50.000
            else if(setor1<50000){
                JOptionPane.showMessageDialog(null,"Minimal penarikan adalah Rp50.000");
                strpin.setText("");
            }
            //jika berhasil
            else{
                tab1 = tab-setor1;
                JOptionPane.showMessageDialog(null,"Penarikan berhasil. \n Saldo anda adalah Rp."+tab1 );}
            strpin.setText("");
            break;

            //kode petunjuk
            case 4:
            JOptionPane.showMessageDialog(null,"Cara Penggunaan Aplikasi\n"
                + "[1] Masukkan PIN dengan benar\n"
                + "[2] Bertransaksilah dengan benar sesuai pilihan\n"
                + "[3] Gunakan Uang sesuai kebutuhan dan rajinlah menabung\n "
                ,"INFO",1);
            strpin.setText("");
            break;

            //kode close
            case 5:
            JOptionPane.showMessageDialog(null,"Terimakasih telah melakukan transaksi.\n Semoga hari anda menyenangkan" );
            this.dispose();
            break;

            //jika tidak memenuhi 1-5
            default:
            JOptionPane.showMessageDialog(null,"Pilihan anda diluar Opsi. Silakan periksa kembali" );
            break;
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField strpin;
    // End of variables declaration//GEN-END:variables
}
